Report Card work done
MKlugman/Report-Card pull request #2
Opened 2024-04-02 19:06 UTC by LeahBineth

2024-04-09 19:31 UTC, MKlugman requested changes

2024-04-09 19:31 UTC, MKlugman commented on 1 tables.sql
> +		constraint ck_ReportCard_PhoneNumber_cannot_be_blank check(PhoneNumber > ''),
PhoneNumber should only be 10 digits and check that's it's only numbers inserted....

2024-04-09 19:31 UTC, MKlugman commented on 1 tables.sql
> +	--AvgScore as ((MathScore + ScienceScore + HistoryScore + EnglishScore) / 4),
AvgScore should be added as column to table.

2024-04-09 19:31 UTC, MKlugman commented on 3 reports.sql
> +	GeneralAvg = ((MathScore + ScienceScore + HistoryScore + EnglishScore) / 4),
if you add GeneralAvg as column, then you don't have to do it manually here or by rest of reports....

2024-04-09 19:31 UTC, MKlugman commented on 3 reports.sql
> +
Either sort this by grade or do as 2 separate reports.

2024-04-09 19:32 UTC, MKlugman commented
I reviewed the work. Thank you! Please see few comments.

2024-04-10 08:01 UTC, LeahBineth commented on 3 reports.sql
> +
LB: I have a `order by r.Grade`... Isn't this what you wanted?

2024-04-10 08:02 UTC, LeahBineth commented
LB: See corrections and one comment... Good luck!

2024-04-11 03:26 UTC, MKlugman commented on 3 reports.sql
> +
Yes Please include `order by r.Grade`
Thank you!

2024-04-11 03:26 UTC, closed without merging